[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"

# Include static assets
[[redirects]]
  from = "/_assets/*"
  to = "/_assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/_chunks/*"
  to = "/_chunks/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/_entry/*"
  to = "/_entry/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
